name: CI for Bazel Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bazel Build
        run: bazel build //tests:test_mymodule

      - name: Run Bazel Tests
        run: bazel test //tests:test_mymodule

      - name: Run Bazel Lint (Optional)
        run: bazel run //:lint
