name: CI for Bazel Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set Working Directory
        run: cd ${{ github.workspace }}

      - name: Install Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Install Python Dependencies
        working-directory: basic_bazel_project
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bazel Build
        working-directory: basic_bazel_project
        run: bazel build //tests:test_mymodule

      - name: Run Bazel Tests
        working-directory: basic_bazel_project
        run: bazel test //tests:test_mymodule

